name: Docker Image CI for GHCR
on:
  push:
    branches: none #[ "master" ]
  pull_request:
    branches: none #[ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GH_PAT }
  IMAGE_VERSION: ${{ secrets.IMAGE_VERSION }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry $REGISTRY
        run: echo $GITHUB_TOKEN | docker login -u $USERNAME --password-stdin
        
      - name: Build the Docker image
        run: docker build --platform=linux/amd64 --file Dockerfile --tag $REGISTRY/$IMAGE_NAME:$IMAGE_VERSION .
      
      - name: Push the Docker image to $REGISTRY
        run: docker push $REGISTRY/$IMAGE_NAME:$IMAGE_VERSION
